language: objective-c
osx_image: xcode7
xcode_project: GithubPilot.xcworkspace
xcode_scheme: GithubPilot
SDK: iphonesimulator9.1

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- xctool -workspace GithubPilot.xcworkspace -scheme GithubPilot -destination "platform=iOS Simulator,name=iPhone 6" clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- xctool test -workspace GithubPilot.xcworkspace -scheme GithubPilotTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
